### ISSUE TITLE
`setup-mac-brew` error: `fatal: --unshallow on a complete repository does not make sense`

### ISSUE THREAD

**Issue by molleweide** [bevry/dorothy#68] opened 2021-11-03 18:03 UTC
```shell
╰ setup-mac-brew

Homebrew is installed.

Updating homebrew...
fatal: --unshallow on a complete repository does not make sense
fatal: --unshallow on a complete repository does not make sense
fatal: --unshallow on a complete repository does not make sense
fatal: --unshallow on a complete repository does not make sense
fatal: --unshallow on a complete repository does not make sense
```

l ran the command earlier today and then everything seems to have install pretty much.

## full stdout

<details>

```shell
╰ setup-mac-brew

Homebrew is installed.

Updating homebrew...
fatal: --unshallow on a complete repository does not make sense
fatal: --unshallow on a complete repository does not make sense
fatal: --unshallow on a complete repository does not make sense
fatal: --unshallow on a complete repository does not make sense
fatal: --unshallow on a complete repository does not make sense
Updated 1 tap (homebrew/core).
No changes to formulae.
==> Casks with 'auto_updates true' or 'version :latest' will not be upgraded; pass `--greedy` to upgrade them.
==> Upgrading 5 outdated packages:
criptext latest -> 0.31.0,2.0.82
drawio 13.0.3 -> 15.4.0
keepassxc 2.5.4 -> 2.6.6
reaper 6.38 -> 6.40
teensy latest -> 1.52
==> Upgrading criptext
==> Downloading https://cdn.criptext.com/Criptext-Email-Desktop/mac/Criptext-latest.dmg
Already downloaded: /Users/hjalmarjakobsson/Library/Caches/Homebrew/downloads/bd6e0fcb366006e5044fd7b38e06562c34dd1a316eeccbe7f2a592c5b3f82bb5--Criptext-latest.dmg
Warning: No checksum defined for cask 'criptext', skipping verification.
==> Purging files for version 0.31.0,2.0.82 of Cask criptext
==> Upgrading drawio
==> Downloading https://github.com/jgraph/drawio-desktop/releases/download/v15.4.0/draw.io-x64-15.4.0.dmg
Already downloaded: /Users/hjalmarjakobsson/Library/Caches/Homebrew/downloads/a8cbe9b1b0b8e98a138e3484edac0d18c4615975939f4cb4e18798fdb92699a9--draw.io-x64-15.4.0.dmg
==> Purging files for version 15.4.0 of Cask drawio
==> Upgrading keepassxc
==> Downloading https://github.com/keepassxreboot/keepassxc/releases/download/2.6.6/KeePassXC-2.6.6-x86_64.dmg
Already downloaded: /Users/hjalmarjakobsson/Library/Caches/Homebrew/downloads/20540289404e2e1b827e38fa1344f1beb52e4d8fdbb0b948190e1d0ff1a79c59--KeePassXC-2.6.6-x86_64.dmg
==> Purging files for version 2.6.6 of Cask keepassxc
==> Upgrading reaper
==> Downloading https://www.reaper.fm/files/6.x/reaper640_x86_64_catalina.dmg
Already downloaded: /Users/hjalmarjakobsson/Library/Caches/Homebrew/downloads/9d8f7dbc63baad5af5f82f55a3df5a785808850f32c6e17f00b10afb1c3e3177--reaper640_x86_64_catalina.dmg
==> Purging files for version 6.40 of Cask reaper
==> Upgrading teensy
==> Downloading https://www.pjrc.com/teensy/teensy.dmg
Already downloaded: /Users/hjalmarjakobsson/Library/Caches/Homebrew/downloads/c578eda858c81809f9e4afc923f88f090d5c666de34faa2c8112f7d39ea87e14--teensy.dmg
Warning: No checksum defined for cask 'teensy', skipping verification.
==> Purging files for version 1.52 of Cask teensy
Error: Problems with multiple casks:
criptext: It seems there is already an App at '/usr/local/Caskroom/criptext/latest/Criptext.app'.
drawio: It seems there is already an App at '/usr/local/Caskroom/drawio/13.0.3/draw.io.app'.
keepassxc: It seems there is already an App at '/usr/local/Caskroom/keepassxc/2.5.4/KeePassXC.app'.
reaper: It seems the App source '/Users/hjalmarjakobsson/reaper/app/RPPTEST/REAPER.app' is not there.
teensy: It seems there is already an App at '/usr/local/Caskroom/teensy/latest/teensy.app'.
```

</details>

**Comment by molleweide** [comment] 2021-11-03 19:33
I posted under homebrew discussions also bc I have never seen the last error before.

**Comment by balupton** [comment] 2021-11-04 12:02
> ```shell
> fatal: --unshallow on a complete repository does not make sense
> fatal: --unshallow on a complete repository does not make sense
> fatal: --unshallow on a complete repository does not make sense
> fatal: --unshallow on a complete repository does not make sense
> fatal: --unshallow on a complete repository does not make sense
> ```

So these, despite the appearance, are not fatal. Dorothy is coded in strict mode, so will actually fail if there is a proper failure. Otherwise it will keep going.

Here is the relevant code in `setup-mac-brew`

``` bash
# Update brew
echo -e '\nUpdating homebrew...'
# trim deprecations
ok silent brew untap caskroom/cask
ok silent brew untap caskroom/fonts
# fix: Error: homebrew-cask is a shallow clone
# uses `ok` as if already done, wil fail with: fatal: --unshallow on a complete repository does not make sense
brewrepodirs="$(echo-subpaths "$(dirname "$(brew --repo homebrew/core)")")"
for directory in $brewrepodirs; do
	ok git -C "$directory" fetch --unshallow
done
```

The issue is one of changing conventions over time with brew, and at one point they recommended shallow clones to prevent the intense load on github, but then that prevented upgrading, so hence the need for --unshallow. All it's saying is that the repo has already been converted to unshallow. 

That said, this of course is bizarre to someone not familiar with what's happening, so it is indeed a bug - as there should be no need to be aware of this. The reason it isn't just a `silent` on it, is because we want to still capture other error messages.

For the other issues you've had:

```

Error: Problems with multiple casks:
criptext: It seems there is already an App at '/usr/local/Caskroom/criptext/latest/Criptext.app'.
drawio: It seems there is already an App at '/usr/local/Caskroom/drawio/13.0.3/draw.io.app'.
keepassxc: It seems there is already an App at '/usr/local/Caskroom/keepassxc/2.5.4/KeePassXC.app'.
reaper: It seems the App source '/Users/hjalmarjakobsson/reaper/app/RPPTEST/REAPER.app' is not there.
teensy: It seems there is already an App at '/usr/local/Caskroom/teensy/latest/teensy.app'.
```

This seems that at some point brew was not cleaned up properly, or simply not cleaned after a prior install. Run `setup-mac-clean` and then try again `setup-mac-brew`. If it is the same issue, then run `brew doctor` and follow the instructions.

**Comment by balupton** [comment] 2021-11-06 07:48
I've nearly finished rewriting the command to address the issues here.

**Comment by molleweide** [comment] 2021-11-06 08:20
Nice!

**Comment by balupton** [comment] 2021-11-06 08:28
Fixed in https://github.com/bevry/dorothy/commit/ae0c5ee18bd4cc56fbf1a9ea315fc949ade42720

You will still need to run `brew doctor` to resolve the issue with:

```
Error: Problems with multiple casks:
criptext: It seems there is already an App at '/usr/local/Caskroom/criptext/latest/Criptext.app'.
drawio: It seems there is already an App at '/usr/local/Caskroom/drawio/13.0.3/draw.io.app'.
keepassxc: It seems there is already an App at '/usr/local/Caskroom/keepassxc/2.5.4/KeePassXC.app'.
reaper: It seems the App source '/Users/hjalmarjakobsson/reaper/app/RPPTEST/REAPER.app' is not there.
teensy: It seems there is already an App at '/usr/local/Caskroom/teensy/latest/teensy.app'.
```

**Closed by balupton** 2021-11-06 08:28 UTC

**Comment by molleweide** [comment] 2021-11-10 18:00
I am going to test and run this tonight.
