### ISSUE TITLE
Hermetic Installation

### ISSUE THREAD

**Issue by reisub0** [bevry/dorothy#150] opened 2022-05-03 12:31 UTC
Forgive me if this is already mentioned somewhere, but is it possible to install and use dorothy in a hermetic way (similar to how [xxh](https://github.com/xxh/xxh/wiki#how-to-set-homeuser-as-home-on-host) works?

The reason I am asking this is because there are some machines where I cannot install packages or get sudo privileges, but looks like the installation process of dorothy for example `setup-util-*` implicitly depends on the package manager of the host. It would be nice if it could install it onto the `.local/bin` or whatever.

Thanks!

**Comment by reisub0** [comment] 2022-05-03 17:03
Well, one of the first things I saw after installing dorothy was the message which told me to install `setup-util-bash` and that's what I tried to do. I did notice that the other ones which were required for the dorothy installation itself (like `sd`, `jq` were installed successfully)

**Comment by balupton** [comment] 2022-05-03 17:16
> Well, one of the first things I saw after installing dorothy was the message which told me to install `setup-util-bash` and that's what I tried to do. I did notice that the other ones which were required for the dorothy installation itself (like `sd`, `jq` were installed successfully)

Ah okay. I'm actually revising the bash installer this week. The problem is that on the latest macOS, bash v3 is the system version, which has several peculiarities. I did some experimentation last week and have determined its possible to have the latest bash installed without homebrew, so that is what will occur once I get these changes out.

**Comment by balupton** [comment] 2022-05-03 18:57
The changes are now pushed that will ensure bash is the latest version, even on macOS installations without brew.

**Comment by balupton** [comment] 2022-05-03 18:59
That said, if you still do not have brew, the installation of `bash-completions` there will cause brew to be installed. I'll work on that later.

**Comment by balupton** [comment] 2022-05-03 19:08
Which OS are you on? As the bash completions will likely still prompt you for sudo if you are on non-macos.

If you can send a PR for `setup-util` that will avoid sudo in your environment, then that will be great.

**Comment by reisub0** [comment] 2022-05-03 20:36
Sorry for not mentioning the platform details: this was on a typical Linux server (Debian 10 x86_64) where I have the inability to use sudo.

I do have a macOS laptop as well which these fixes will anyway be useful for so thanks a lot!

On a side note:
I really like the idea and vision of Dorothy, but most of the times I've tried to install dorothy, something or the other has been broken :( 

I know it's a lot of moving parts and please excuse the unsolicited suggestion but maybe consider moving active development to another branch? Or perhaps the official install instructions should point at something like `https://github.com/bevry/dorothy/archive/refs/tags/0.5.0.tar.gz` so that the installation experience would be consistent and not a surprise.

**Comment by reisub0** [comment] 2022-05-03 20:38
Regarding the PR, I will definitely try to see what I can do if I get some time this week.

**Comment by balupton** [comment] 2022-05-03 22:59
> I really like the idea and vision of Dorothy, but most of the times I've tried to install dorothy, something or the other has been broken :(
> 
> I know it's a lot of moving parts and please excuse the unsolicited suggestion but maybe consider moving active development to another branch? Or perhaps the official install instructions should point at something like `https://github.com/bevry/dorothy/archive/refs/tags/0.5.0.tar.gz` so that the installation experience would be consistent and not a surprise.

Completely agree. Although right now I'm 100% focused on getting the public launch milestone completed https://github.com/bevry/dorothy/milestone/1 once that is done, these rough and volatile aspects of Dorothy will be sorted.

**Comment by balupton** [comment] 2022-09-03 18:11
@reisub0 besides #142 and outdated documentation, Dorothy should now be stable and reliable enough for wider adoption.

**Comment by balupton** [comment] 2022-09-07 00:25
Going to close this issue as I believe the trial, install, and xdg modes support this request.

**Closed by balupton** 2022-09-07 00:25 UTC
